# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/engine/project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/engine/project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/engine/project/CMakeFiles /home/engine/project//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/engine/project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named x

# Build rule for target.
x : cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 x
.PHONY : x

# fast build rule for target.
x/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/x.dir/build.make CMakeFiles/x.dir/build
.PHONY : x/fast

src/Aimbot.o: src/Aimbot.cpp.o
.PHONY : src/Aimbot.o

# target to build an object file
src/Aimbot.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/x.dir/build.make CMakeFiles/x.dir/src/Aimbot.cpp.o
.PHONY : src/Aimbot.cpp.o

src/Aimbot.i: src/Aimbot.cpp.i
.PHONY : src/Aimbot.i

# target to preprocess a source file
src/Aimbot.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/x.dir/build.make CMakeFiles/x.dir/src/Aimbot.cpp.i
.PHONY : src/Aimbot.cpp.i

src/Aimbot.s: src/Aimbot.cpp.s
.PHONY : src/Aimbot.s

# target to generate assembly for a file
src/Aimbot.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/x.dir/build.make CMakeFiles/x.dir/src/Aimbot.cpp.s
.PHONY : src/Aimbot.cpp.s

src/Config.o: src/Config.cpp.o
.PHONY : src/Config.o

# target to build an object file
src/Config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/x.dir/build.make CMakeFiles/x.dir/src/Config.cpp.o
.PHONY : src/Config.cpp.o

src/Config.i: src/Config.cpp.i
.PHONY : src/Config.i

# target to preprocess a source file
src/Config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/x.dir/build.make CMakeFiles/x.dir/src/Config.cpp.i
.PHONY : src/Config.cpp.i

src/Config.s: src/Config.cpp.s
.PHONY : src/Config.s

# target to generate assembly for a file
src/Config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/x.dir/build.make CMakeFiles/x.dir/src/Config.cpp.s
.PHONY : src/Config.cpp.s

src/Drawing.o: src/Drawing.cpp.o
.PHONY : src/Drawing.o

# target to build an object file
src/Drawing.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/x.dir/build.make CMakeFiles/x.dir/src/Drawing.cpp.o
.PHONY : src/Drawing.cpp.o

src/Drawing.i: src/Drawing.cpp.i
.PHONY : src/Drawing.i

# target to preprocess a source file
src/Drawing.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/x.dir/build.make CMakeFiles/x.dir/src/Drawing.cpp.i
.PHONY : src/Drawing.cpp.i

src/Drawing.s: src/Drawing.cpp.s
.PHONY : src/Drawing.s

# target to generate assembly for a file
src/Drawing.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/x.dir/build.make CMakeFiles/x.dir/src/Drawing.cpp.s
.PHONY : src/Drawing.cpp.s

src/ESP.o: src/ESP.cpp.o
.PHONY : src/ESP.o

# target to build an object file
src/ESP.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/x.dir/build.make CMakeFiles/x.dir/src/ESP.cpp.o
.PHONY : src/ESP.cpp.o

src/ESP.i: src/ESP.cpp.i
.PHONY : src/ESP.i

# target to preprocess a source file
src/ESP.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/x.dir/build.make CMakeFiles/x.dir/src/ESP.cpp.i
.PHONY : src/ESP.cpp.i

src/ESP.s: src/ESP.cpp.s
.PHONY : src/ESP.s

# target to generate assembly for a file
src/ESP.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/x.dir/build.make CMakeFiles/x.dir/src/ESP.cpp.s
.PHONY : src/ESP.cpp.s

src/GUI.o: src/GUI.cpp.o
.PHONY : src/GUI.o

# target to build an object file
src/GUI.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/x.dir/build.make CMakeFiles/x.dir/src/GUI.cpp.o
.PHONY : src/GUI.cpp.o

src/GUI.i: src/GUI.cpp.i
.PHONY : src/GUI.i

# target to preprocess a source file
src/GUI.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/x.dir/build.make CMakeFiles/x.dir/src/GUI.cpp.i
.PHONY : src/GUI.cpp.i

src/GUI.s: src/GUI.cpp.s
.PHONY : src/GUI.s

# target to generate assembly for a file
src/GUI.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/x.dir/build.make CMakeFiles/x.dir/src/GUI.cpp.s
.PHONY : src/GUI.cpp.s

src/Game.o: src/Game.cpp.o
.PHONY : src/Game.o

# target to build an object file
src/Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/x.dir/build.make CMakeFiles/x.dir/src/Game.cpp.o
.PHONY : src/Game.cpp.o

src/Game.i: src/Game.cpp.i
.PHONY : src/Game.i

# target to preprocess a source file
src/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/x.dir/build.make CMakeFiles/x.dir/src/Game.cpp.i
.PHONY : src/Game.cpp.i

src/Game.s: src/Game.cpp.s
.PHONY : src/Game.s

# target to generate assembly for a file
src/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/x.dir/build.make CMakeFiles/x.dir/src/Game.cpp.s
.PHONY : src/Game.cpp.s

src/Player.o: src/Player.cpp.o
.PHONY : src/Player.o

# target to build an object file
src/Player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/x.dir/build.make CMakeFiles/x.dir/src/Player.cpp.o
.PHONY : src/Player.cpp.o

src/Player.i: src/Player.cpp.i
.PHONY : src/Player.i

# target to preprocess a source file
src/Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/x.dir/build.make CMakeFiles/x.dir/src/Player.cpp.i
.PHONY : src/Player.cpp.i

src/Player.s: src/Player.cpp.s
.PHONY : src/Player.s

# target to generate assembly for a file
src/Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/x.dir/build.make CMakeFiles/x.dir/src/Player.cpp.s
.PHONY : src/Player.cpp.s

src/imgui.o: src/imgui.cpp.o
.PHONY : src/imgui.o

# target to build an object file
src/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/x.dir/build.make CMakeFiles/x.dir/src/imgui.cpp.o
.PHONY : src/imgui.cpp.o

src/imgui.i: src/imgui.cpp.i
.PHONY : src/imgui.i

# target to preprocess a source file
src/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/x.dir/build.make CMakeFiles/x.dir/src/imgui.cpp.i
.PHONY : src/imgui.cpp.i

src/imgui.s: src/imgui.cpp.s
.PHONY : src/imgui.s

# target to generate assembly for a file
src/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/x.dir/build.make CMakeFiles/x.dir/src/imgui.cpp.s
.PHONY : src/imgui.cpp.s

src/imgui_draw.o: src/imgui_draw.cpp.o
.PHONY : src/imgui_draw.o

# target to build an object file
src/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/x.dir/build.make CMakeFiles/x.dir/src/imgui_draw.cpp.o
.PHONY : src/imgui_draw.cpp.o

src/imgui_draw.i: src/imgui_draw.cpp.i
.PHONY : src/imgui_draw.i

# target to preprocess a source file
src/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/x.dir/build.make CMakeFiles/x.dir/src/imgui_draw.cpp.i
.PHONY : src/imgui_draw.cpp.i

src/imgui_draw.s: src/imgui_draw.cpp.s
.PHONY : src/imgui_draw.s

# target to generate assembly for a file
src/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/x.dir/build.make CMakeFiles/x.dir/src/imgui_draw.cpp.s
.PHONY : src/imgui_draw.cpp.s

src/imgui_impl_android.o: src/imgui_impl_android.cpp.o
.PHONY : src/imgui_impl_android.o

# target to build an object file
src/imgui_impl_android.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/x.dir/build.make CMakeFiles/x.dir/src/imgui_impl_android.cpp.o
.PHONY : src/imgui_impl_android.cpp.o

src/imgui_impl_android.i: src/imgui_impl_android.cpp.i
.PHONY : src/imgui_impl_android.i

# target to preprocess a source file
src/imgui_impl_android.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/x.dir/build.make CMakeFiles/x.dir/src/imgui_impl_android.cpp.i
.PHONY : src/imgui_impl_android.cpp.i

src/imgui_impl_android.s: src/imgui_impl_android.cpp.s
.PHONY : src/imgui_impl_android.s

# target to generate assembly for a file
src/imgui_impl_android.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/x.dir/build.make CMakeFiles/x.dir/src/imgui_impl_android.cpp.s
.PHONY : src/imgui_impl_android.cpp.s

src/imgui_impl_opengl3.o: src/imgui_impl_opengl3.cpp.o
.PHONY : src/imgui_impl_opengl3.o

# target to build an object file
src/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/x.dir/build.make CMakeFiles/x.dir/src/imgui_impl_opengl3.cpp.o
.PHONY : src/imgui_impl_opengl3.cpp.o

src/imgui_impl_opengl3.i: src/imgui_impl_opengl3.cpp.i
.PHONY : src/imgui_impl_opengl3.i

# target to preprocess a source file
src/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/x.dir/build.make CMakeFiles/x.dir/src/imgui_impl_opengl3.cpp.i
.PHONY : src/imgui_impl_opengl3.cpp.i

src/imgui_impl_opengl3.s: src/imgui_impl_opengl3.cpp.s
.PHONY : src/imgui_impl_opengl3.s

# target to generate assembly for a file
src/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/x.dir/build.make CMakeFiles/x.dir/src/imgui_impl_opengl3.cpp.s
.PHONY : src/imgui_impl_opengl3.cpp.s

src/imgui_tables.o: src/imgui_tables.cpp.o
.PHONY : src/imgui_tables.o

# target to build an object file
src/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/x.dir/build.make CMakeFiles/x.dir/src/imgui_tables.cpp.o
.PHONY : src/imgui_tables.cpp.o

src/imgui_tables.i: src/imgui_tables.cpp.i
.PHONY : src/imgui_tables.i

# target to preprocess a source file
src/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/x.dir/build.make CMakeFiles/x.dir/src/imgui_tables.cpp.i
.PHONY : src/imgui_tables.cpp.i

src/imgui_tables.s: src/imgui_tables.cpp.s
.PHONY : src/imgui_tables.s

# target to generate assembly for a file
src/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/x.dir/build.make CMakeFiles/x.dir/src/imgui_tables.cpp.s
.PHONY : src/imgui_tables.cpp.s

src/imgui_widgets.o: src/imgui_widgets.cpp.o
.PHONY : src/imgui_widgets.o

# target to build an object file
src/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/x.dir/build.make CMakeFiles/x.dir/src/imgui_widgets.cpp.o
.PHONY : src/imgui_widgets.cpp.o

src/imgui_widgets.i: src/imgui_widgets.cpp.i
.PHONY : src/imgui_widgets.i

# target to preprocess a source file
src/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/x.dir/build.make CMakeFiles/x.dir/src/imgui_widgets.cpp.i
.PHONY : src/imgui_widgets.cpp.i

src/imgui_widgets.s: src/imgui_widgets.cpp.s
.PHONY : src/imgui_widgets.s

# target to generate assembly for a file
src/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/x.dir/build.make CMakeFiles/x.dir/src/imgui_widgets.cpp.s
.PHONY : src/imgui_widgets.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... x"
	@echo "... src/Aimbot.o"
	@echo "... src/Aimbot.i"
	@echo "... src/Aimbot.s"
	@echo "... src/Config.o"
	@echo "... src/Config.i"
	@echo "... src/Config.s"
	@echo "... src/Drawing.o"
	@echo "... src/Drawing.i"
	@echo "... src/Drawing.s"
	@echo "... src/ESP.o"
	@echo "... src/ESP.i"
	@echo "... src/ESP.s"
	@echo "... src/GUI.o"
	@echo "... src/GUI.i"
	@echo "... src/GUI.s"
	@echo "... src/Game.o"
	@echo "... src/Game.i"
	@echo "... src/Game.s"
	@echo "... src/Player.o"
	@echo "... src/Player.i"
	@echo "... src/Player.s"
	@echo "... src/imgui.o"
	@echo "... src/imgui.i"
	@echo "... src/imgui.s"
	@echo "... src/imgui_draw.o"
	@echo "... src/imgui_draw.i"
	@echo "... src/imgui_draw.s"
	@echo "... src/imgui_impl_android.o"
	@echo "... src/imgui_impl_android.i"
	@echo "... src/imgui_impl_android.s"
	@echo "... src/imgui_impl_opengl3.o"
	@echo "... src/imgui_impl_opengl3.i"
	@echo "... src/imgui_impl_opengl3.s"
	@echo "... src/imgui_tables.o"
	@echo "... src/imgui_tables.i"
	@echo "... src/imgui_tables.s"
	@echo "... src/imgui_widgets.o"
	@echo "... src/imgui_widgets.i"
	@echo "... src/imgui_widgets.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

